# Generated by Django 6.0.7 on 2026-07-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
